version: '3.8'
services:
  database:
    container_name: msu-mysql-db
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306" # Map container's port 3306 to host's port 3307
    environment:
      MYSQL_ROOT_PASSWORD: mysql123123
      MYSQL_DATABASE: msu_course_scheduling
    volumes:
      - db_data:/var/lib/mysql # Persist MySQL data

  app:
    container_name: msu-course-scheduling-app
    build:
      context: .
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/msu_course_scheduling
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql123123
    ports:
      - "8080:8080"
    command: >
      sh -c "while ! nc -z database 3306; do
        echo 'Waiting for MySQL to be ready...'; sleep 2;
      done;
      java -jar app.jar"

volumes:
  db_data:
